### ISSUE TITLE
Add notes to the README about TF_Accept

### ISSUE THREAD

**Issue by jdavidberger** [MightyPork/TinyFrame#13]
The usage notes are very good about saying how to set up the write side, but mention nothing about the read side. I'd add a blurb about 'TF_Accept', but I'm still setting up my particular usage

**Comment by MightyPork** [comment]
Hello, good to hear someone using the library :)

Feel free to send a Pull Request for the README, but the usage of [`TF_Accept`](https://github.com/MightyPork/TinyFrame/blob/master/TinyFrame.h#L193) is really straightforward: you just call it from your interrupt routine or wherever you receive bytes.

The clients are equal, so both will implement this in a similar way.

Use `TF_AcceptChar(tf, byte)` if there's just one byte at a time - `TF_Accept(tf, bytes, count)` only implements a for loop for convenience.

**Comment by jdavidberger** [comment]
PR made. It also looks like you might have forgotten 'demo/multipart_tx/' files; thought I'd let you know

**Comment by MightyPork** [comment]
i'm not sure there ever was such a folder, however, there is `simple_multipart/`. Where did you see it referenced?

**Comment by jdavidberger** [comment]
https://github.com/MightyPork/TinyFrame/blob/master/CMakeLists.txt#L12

**Comment by MightyPork** [comment]
oh, right, I should remove that, thats some leftover. It's a dummy file for CLion, the examples are built using normal makefiles
