### ISSUE TITLE
A demo of using the Payloadparser

### ISSUE THREAD

**Issue by Irdroid** [MightyPork/TinyFrame#24]
Hello, 

Can you please make a simple demo of using the payload parser . 

I did this and I am gettings segfaults.

```
`#include <stdio.h>
#include "./utilities/payload_parser.h"

PayloadParser *pp;

unsigned char buff[] = "Hello";
unsigned char *buf = buff;
bool emptyhandler()
{
printf("Error\n");
return true;
}

int main()
{
pp_start(buf, sizeof(buff), emptyhandler);
unsigned char ping = pp_u8(pp);
return 0;
}
`
```

**Comment by MightyPork** [comment]
pp_start returns the payload parser struct, you need something like

```
PayloadParser pp = pp_start(buf, sizeof(buff), emptyhandler);
```

It's not a pointer.

Look in the header to see how that works: https://github.com/MightyPork/TinyFrame/blob/master/utilities/payload_parser.h#L55

**Comment by Irdroid** [comment]
Thank you!
